db:
  user: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  database: "short_url"
  tablePrefix: ""
  enableDBInit: true # 是否需要初始化数据库
  slowThreshold: 200000000 # 查询时间大于该值的则为慢 sql，单位 ns
  skipDefaultTransaction: false # 默认不开启事务

redis:
  host: "localhost"
  port: "6379"
  prefix: "short_url"
  expiration: 86400 # 24 小时，单位 秒

# 如果指定了正数 size，则 percentage 不生效，否则 size 的值将由 percentage 计算得出
lru:
  size: 500000 # 该数值大概为 4GB 内存的 3% 所计算出的 lru size
  percentage: 3 # lru 可使用的内存占机器最大内存的百分比，单位 %
  expiration: 28800 # 8 小时，单位 秒

log:
  mode: "dev"
  outputPaths:
    - "./log/log.txt"
  errorOutputPaths:
    - "./log/error_output.txt"

short_url:
  suffix: "_TO404HANGA"
  
job:
  timeout: 30
  # expr: "@every 1m" # 每分钟
  expr: "0 0 4 * * *" # 每天凌晨 4 点执行定时任务
  enabled: true

grpc:
  server:
    port: 0  # 填 0 随机分配空闲端口
    etcdTTL: 60
    etcdAddr: "127.0.0.1:2379"

etcd:
  endpoints:
    - "127.0.0.1:2379"