// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"short_url/ioc"
	"short_url/repository/dao"
	"short_url/web"
)

// Injectors from wire.go:

func Init() *gin.Engine {
	cmdable := ioc.InitRedis()
	shortUrlCache := ioc.InitRedisCache(cmdable)
	db := ioc.InitDB()
	logger := ioc.InitLogger()
	shortUrlDAO := dao.NewGormShortUrlDAO(db, logger)
	shortUrlRepository := ioc.InitCachedRepository(shortUrlCache, shortUrlDAO, logger)
	shortUrlService := ioc.InitService(shortUrlRepository, logger)
	apiHandler := web.NewApiHandler(shortUrlService)
	serverHandler := web.NewServerHandler(shortUrlService)
	engine := ioc.InitWebServer(apiHandler, serverHandler)
	return engine
}
