// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"short_url/ioc"
	"short_url/repository/dao"
	"short_url/web"
)

// Injectors from wire.go:

func Init() *App {
	cmdable := ioc.InitRedis()
	shortUrlCache := ioc.InitRedisCache(cmdable)
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	shortUrlDAO := dao.NewGormShortUrlDAO(db, logger)
	shortUrlRepository := ioc.InitCachedRepository(shortUrlCache, shortUrlDAO, logger)
	shortUrlService := ioc.InitService(shortUrlRepository, logger)
	apiHandler := web.NewApiHandler(shortUrlService)
	serverHandler := web.NewServerHandler(shortUrlService)
	v := ioc.InitGinMiddleware(logger)
	engine := ioc.InitWebServer(apiHandler, serverHandler, v)
	job := ioc.InitCleanerJob(shortUrlService)
	cron := ioc.InitJobs(logger, job)
	app := &App{
		server: engine,
		cron:   cron,
	}
	return app
}
