// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rpc.proto

package short_url_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShortUrlService_GenerateShortUrl_FullMethodName = "/short_url.v1.ShortUrlService/GenerateShortUrl"
	ShortUrlService_GetOriginUrl_FullMethodName     = "/short_url.v1.ShortUrlService/GetOriginUrl"
)

// ShortUrlServiceClient is the client API for ShortUrlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortUrlServiceClient interface {
	GenerateShortUrl(ctx context.Context, in *GenerateShortUrlRequest, opts ...grpc.CallOption) (*GenerateShortUrlResponse, error)
	GetOriginUrl(ctx context.Context, in *GetOriginUrlRequest, opts ...grpc.CallOption) (*GetOriginUrlResponse, error)
}

type shortUrlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortUrlServiceClient(cc grpc.ClientConnInterface) ShortUrlServiceClient {
	return &shortUrlServiceClient{cc}
}

func (c *shortUrlServiceClient) GenerateShortUrl(ctx context.Context, in *GenerateShortUrlRequest, opts ...grpc.CallOption) (*GenerateShortUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateShortUrlResponse)
	err := c.cc.Invoke(ctx, ShortUrlService_GenerateShortUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortUrlServiceClient) GetOriginUrl(ctx context.Context, in *GetOriginUrlRequest, opts ...grpc.CallOption) (*GetOriginUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOriginUrlResponse)
	err := c.cc.Invoke(ctx, ShortUrlService_GetOriginUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortUrlServiceServer is the server API for ShortUrlService service.
// All implementations must embed UnimplementedShortUrlServiceServer
// for forward compatibility.
type ShortUrlServiceServer interface {
	GenerateShortUrl(context.Context, *GenerateShortUrlRequest) (*GenerateShortUrlResponse, error)
	GetOriginUrl(context.Context, *GetOriginUrlRequest) (*GetOriginUrlResponse, error)
	mustEmbedUnimplementedShortUrlServiceServer()
}

// UnimplementedShortUrlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortUrlServiceServer struct{}

func (UnimplementedShortUrlServiceServer) GenerateShortUrl(context.Context, *GenerateShortUrlRequest) (*GenerateShortUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShortUrl not implemented")
}
func (UnimplementedShortUrlServiceServer) GetOriginUrl(context.Context, *GetOriginUrlRequest) (*GetOriginUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOriginUrl not implemented")
}
func (UnimplementedShortUrlServiceServer) mustEmbedUnimplementedShortUrlServiceServer() {}
func (UnimplementedShortUrlServiceServer) testEmbeddedByValue()                         {}

// UnsafeShortUrlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortUrlServiceServer will
// result in compilation errors.
type UnsafeShortUrlServiceServer interface {
	mustEmbedUnimplementedShortUrlServiceServer()
}

func RegisterShortUrlServiceServer(s grpc.ServiceRegistrar, srv ShortUrlServiceServer) {
	// If the following call pancis, it indicates UnimplementedShortUrlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShortUrlService_ServiceDesc, srv)
}

func _ShortUrlService_GenerateShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateShortUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortUrlServiceServer).GenerateShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortUrlService_GenerateShortUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortUrlServiceServer).GenerateShortUrl(ctx, req.(*GenerateShortUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortUrlService_GetOriginUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOriginUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortUrlServiceServer).GetOriginUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShortUrlService_GetOriginUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortUrlServiceServer).GetOriginUrl(ctx, req.(*GetOriginUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortUrlService_ServiceDesc is the grpc.ServiceDesc for ShortUrlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortUrlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "short_url.v1.ShortUrlService",
	HandlerType: (*ShortUrlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateShortUrl",
			Handler:    _ShortUrlService_GenerateShortUrl_Handler,
		},
		{
			MethodName: "GetOriginUrl",
			Handler:    _ShortUrlService_GetOriginUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
