app:
  addr: ":8080"

log:
  mode: "prod"
  outputPaths:
    - "./log/log.txt"
  errorOutputPaths:
    - "./log/error_output.txt"

etcd:
  addrs:
    - "localhost:2379"

grpc:
  client:
    shortUrl:
      target: "etcd:///service/short_url"
      Secure: false
  
short_url:
  weights: [1009, 1231, 1031, 1013, 1019, 1021]