app:
  addr: ":8080"

log:
  mode: "dev"
  outputPaths:
    - "./log/log.txt"
  errorOutputPaths:
    - "./log/error_output.txt"

etcd:
  addrs:
    - "localhost:2379"

grpc:
  client:
    shortUrl:
      target: "etcd:///service/short_url"
      Secure: false